### ISSUE TITLE
Trying to Install on Joomla 3.9.23

### ISSUE THREAD

**Issue by Domgarth** [nikosdion/combinator#2]
I get exactly the same error messages as dgjoom had on Joomla 4

JInstaller: :Install: Can't find Joomla XML setup file.
Unable to detect manifest file.

**Comment by nikosdion** [comment]
This plugin is only for Joomla 3.

Joomla 4 allows developers to easily make their static resources load deferred, supports HTTP/2 Push etc. There is no need for this plugin in Joomla 4. In fact, trying to use it with Joomla 4 would break your site in most cases. As a result it was never made compatible with Joomla 4.

**Comment by Domgarth** [comment]
I get the install errors when trying to install your plugin on Joomla 3.9.23

I understand what you are saying about the improvements in Joomla 4, but I want to improve our joomla 3 site now before we migrate to Joomla 4

**Comment by nikosdion** [comment]
Try installing https://github.com/nikosdion/combinator/releases/tag/1.0.1

**Comment by Domgarth** [comment]
Thanks. Installs Perfectly!
